name: Gradle Build for Groovy DSL
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./gradle-groovy-dsl

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Test served React page
      run: |
        # Run application for 10 seconds:
        timeout -s KILL 10 java -jar java-app/build/libs/java-app-0.0.1-SNAPSHOT.jar &

        # Wait 5 seconds for application to start then check for "React App" in the served page:
        sleep 5 && curl http://localhost:8080 | grep "React App"

        # This doesn't test the JavaScript because curl doesn't support it,
        # but it helps to check that the Spring Boot application can serve
        # up the React page.  More sophisticated E2E tests could be done
        # with a tool like Cypress.
