name: Gradle Build for Kotlin DSL
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./gradle-kotlin-dsl

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Execute Gradle build
      run: ./gradlew build
